### ISSUE TITLE
Section for Kehan Zou.

### ISSUE THREAD

**Issue by brantr** [brantr/astr-119-section-assignments#37]
Assign Kehan Zou to a section.

**Comment by PetersonZou** [comment]
[hello-world-Kehan-Z.py.txt](https://github.com/brantr/astr-119-section-assignments/files/2440936/hello-world-Kehan-Z.py.txt)

**Comment by brantr** [comment]
Hi Kehan, 

Please issue a pull request following the instructions from the first day of class.  You can look at the slides from the Canvas site if you need a refresher on how to do this.

Thanks,
Brant
