### ISSUE TITLE
Request for Section for Thomas Seever

### ISSUE THREAD

**Issue by tiseever** [brantr/astr-119-section-assignments#59]
My name is not listed here because I am on the waitlist. I would like to have an issue posted so I can get into a section. If there is anything I can do to help ensure that I am enrolled in the class please contact me at tseever@ucsc.edu.

**Comment by brantr** [comment]
I'll work on this offline and correspond via email.  I've made a different issue (#71 ) in the standard format.  Please submit a pull request to close that issue for the homework.  Thanks!
