### ISSUE TITLE
Typo in Instructions and inability to add new branch

### ISSUE THREAD

**Issue by jcmcmurry** [brantr/astr-119-section-assignments#60]
Within the repository comment the '!' is missing between the # and /

There also appears to be a lack of ability to create branches for other users.

**Comment by jsillman** [comment]
Seconded- I'm also unable to create a branch. Please fix this soon

![screen shot 2018-09-27 at 11 55 53 am](https://user-images.githubusercontent.com/43651621/46168134-7883b280-c24c-11e8-8295-a5e14d2d3fbb.png)

**Comment by brantr** [comment]
Working on it now.  The proper workflow is to fork to make a branch in your own account and then issue a pull request from that branch.
